import copy
import importlib.util
from pathlib import Path
import sys

import numpy as np
from loguru import logger as lg
from scipy.constants import speed_of_light as c0

from pynlin.system import System
from pynlin.utils import _toml_load

_DEFAULT_GNLSE_NLI_PY = Path("/home/lorenzi/sw/gnlse-python/examples/nli/nli.py")
_DEFAULT_GNLSE_WDM_CONFIG = Path("/home/lorenzi/sw/gnlse-python/input/wdm_nli_config.toml")

_SSFM_TOML_HEADER = [
    "Autogenerated runtime TOML for SSFM NLI evaluation from PyNLIN scaling scripts.",
    "This file is consumed by gnlse-python/examples/nli/nli.py::run_wdm_nli_simulation().",
    "Section names, field names, units and conventions follow the gnlse script/template exactly.",
    "Only scenario values are mapped from the current PyNLIN system (e.g., spacing, launch power, fiber parameters).",
    "The WDM channel count is intentionally forced to 5 for SSFM compatibility in this workflow.",
    "For the constant-profile comparison mode, fiber attenuation is set to zero so the SSFM run is lossless.",
    "The symbol rate follows the system baud rate; samples_per_symbol is recomputed per iteration.",
    "samples_per_symbol is set to the minimum integer that satisfies the Nyquist-band condition for the 5-channel plan.",
]


def _toml_value_to_text(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, np.integer)):
        return str(int(value))
    if isinstance(value, (float, np.floating)):
        val = float(value)
        if not np.isfinite(val):
            raise ValueError(f"Cannot serialize non-finite float to TOML: {val}")
        return f"{val:.12g}"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value_to_text(v) for v in value) + "]"
    raise TypeError(f"Unsupported TOML value type: {type(value)!r}")


def _toml_dict_to_lines(data: dict, section: tuple[str, ...] = ()) -> list[str]:
    lines: list[str] = []
    scalar_items: list[tuple[str, object]] = []
    child_items: list[tuple[str, dict]] = []
    for key, value in data.items():
        if isinstance(value, dict):
            child_items.append((key, value))
        else:
            scalar_items.append((key, value))

    if section:
        lines.append(f"[{'.'.join(section)}]")
    for key, value in scalar_items:
        lines.append(f"{key} = {_toml_value_to_text(value)}")
    if scalar_items and child_items:
        lines.append("")

    for idx, (key, child) in enumerate(child_items):
        lines.extend(_toml_dict_to_lines(child, section=section + (key,)))
        if idx < len(child_items) - 1:
            lines.append("")
    return lines


def _write_toml(path: Path, data: dict, comments: list[str] | None = None) -> None:
    lines = _toml_dict_to_lines(data)
    if comments:
        header = [f"# {line}" for line in comments]
        lines = header + [""] + lines
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _load_run_wdm_nli_simulation(nli_script_path: Path):
    module_name = "gnlse_examples_nli_runtime"
    module_dir = str(nli_script_path.parent)
    if module_dir not in sys.path:
        sys.path.insert(0, module_dir)
    spec = importlib.util.spec_from_file_location(module_name, nli_script_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Unable to import module from {nli_script_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    run_fn = getattr(module, "run_wdm_nli_simulation", None)
    if run_fn is None:
        raise AttributeError(f"run_wdm_nli_simulation not found in {nli_script_path}")
    return run_fn


def _safe_beta2_ps2_per_m(system: System, channel_idx: int) -> float:
    freqs = system.wdm.frequency_grid()
    try:
        _, beta2_grid = system.beta_grids(freqs)
        beta2_val = float(np.asarray(beta2_grid, dtype=float)[0, channel_idx])
    except Exception:
        beta2_val = float(getattr(system.fiber, "beta2", 0.0) or 0.0)
    return beta2_val * 1e24


def _compute_min_samples_per_symbol_for_nyquist(
    *,
    symbol_rate_gbd: float,
    channel_spacing_thz: float,
    n_channels: int,
    pulse_shape: str,
    rrc_rolloff: float,
) -> int:
    symbol_rate_thz = float(symbol_rate_gbd) * 1e-3
    if symbol_rate_thz <= 0.0:
        raise ValueError("symbol_rate_gbd must be positive")
    max_offset_thz = channel_spacing_thz * (n_channels - 1) / 2.0
    if pulse_shape == "rrc":
        effective_bw_factor = 1.0 + float(rrc_rolloff)
    else:
        effective_bw_factor = 1.0
    rhs = (2.0 * max_offset_thz / symbol_rate_thz) + effective_bw_factor
    return max(int(np.ceil(rhs)), 2)


def _build_ssfm_runtime_config(
    *,
    template_cfg: dict,
    system: System,
    launch_channel_w: float,
    channel_idx: int,
    out_dir: Path,
    sweep_tag: str,
) -> dict:
    cfg = copy.deepcopy(template_cfg)
    mod = cfg.setdefault("modulation", {})
    mod.setdefault("order", 16)
    mod.setdefault("pulse_shape", "nyquist_rect")
    mod.setdefault("rrc_rolloff", 0.0)
    mod.setdefault("rrc_span_symbols", 12)
    mod.setdefault("n_symbols", 4096)
    pulse_shape = str(mod.get("pulse_shape", "nyquist_rect"))
    rrc_rolloff = float(mod.get("rrc_rolloff", 0.0))
    
    # Preserve symbol_rate_gbd from template if available; otherwise use system baud rate
    if "symbol_rate_gbd" not in mod:
        mod["symbol_rate_gbd"] = float(system.pulse.baud_rate * 1e-9)

    wdm = cfg.setdefault("wdm", {})
    wdm["n_channels"] = 5
    spacing = float(system.channel_spacing) if system.channel_spacing is not None else float(np.mean(np.diff(system.wdm.frequency_grid())))
    wdm["channel_spacing_thz"] = float(spacing * 1e-12)

    power_single_pol_w = float(launch_channel_w)
    power_dual_pol_w = power_single_pol_w * 2.0
    lg.warning(
        "SSFM power conversion: single-pol {:.6e} W -> dual-pol {:.6e} W",
        power_single_pol_w,
        power_dual_pol_w,
    )

    if "power_per_channel_w" not in wdm:
        wdm["power_per_channel_w"] = power_dual_pol_w

    mod["samples_per_symbol"] = _compute_min_samples_per_symbol_for_nyquist(
        symbol_rate_gbd=float(mod["symbol_rate_gbd"]),
        channel_spacing_thz=float(wdm["channel_spacing_thz"]),
        n_channels=int(wdm["n_channels"]),
        pulse_shape=pulse_shape,
        rrc_rolloff=rrc_rolloff,
    )

    freqs = system.wdm.frequency_grid()
    center_freq = float(freqs[channel_idx])
    fiber = cfg.setdefault("fiber", {})
    fiber["wavelength_nm"] = float((c0 / center_freq) * 1e9)
    fiber["fiber_length_m"] = float(system.fiber_length)

    gamma_raw = float(getattr(system.fiber, "gamma", 1.3e-3))
    gamma_scaled = gamma_raw * (8.0 / 9.0)
    fiber["nonlinearity"] = gamma_scaled
    lg.warning(
        "SSFM gamma conversion: single-pol {:.6e} -> dual-pol {:.6e} W⁻¹m⁻¹",
        gamma_raw,
        gamma_scaled,
    )

    fiber["loss_db_per_m"] = 0.0
    fiber["betas"] = [float(_safe_beta2_ps2_per_m(system, channel_idx))]

    output = cfg.setdefault("output", {})
    output["save_dir"] = str(out_dir / "ssfm")
    output["save_name"] = f"ssfm_constellation_{sweep_tag}.png"
    output["show_plot"] = False

    cache = cfg.setdefault("cache", {})
    cache.setdefault("mode", "recompute")

    monte_carlo = cfg.setdefault("monte_carlo", {})
    monte_carlo.setdefault("n_trials", 1)
    monte_carlo.setdefault("rng_seed", 1234)

    solver = cfg.setdefault("solver", {})
    solver.setdefault("z_saves", 2)
    solver.setdefault("rtol", 1e-5)
    solver.setdefault("atol", 1e-7)
    solver.setdefault("ssfm_max_nonlinear_phase_deg", 0.02)
    solver.setdefault("ssfm_max_step_m", 1000)
    solver.setdefault("propagation_backend", "gnlse")
    return cfg


def _extract_ssfm_center_nli_w(payload: dict) -> float | None:
    try:
        value = payload["power_report"]["center_channel"]["nli_power_avg_w"]
        if value is None:
            return None
        out_dual_pol = float(value)
        if not np.isfinite(out_dual_pol):
            return None
        out_single_pol = out_dual_pol / 2.0
        lg.warning(
            "SSFM output conversion: dual-pol {:.6e} W -> single-pol {:.6e} W",
            out_dual_pol,
            out_single_pol,
        )
        return out_single_pol
    except Exception:
        return None


def prepare_ssfm_runtime(out_dir: Path, runtime_toml_name: str = "ssfm.toml") -> dict | None:
    nli_script_path = Path(str(Path.home() / "sw" / "gnlse-python" / "examples" / "nli" / "nli.py"))
    cfg_template_path = Path(str(Path.home() / "sw" / "gnlse-python" / "input" / "wdm_nli_config.toml"))
    if not nli_script_path.exists():
        nli_script_path = _DEFAULT_GNLSE_NLI_PY
    if not cfg_template_path.exists():
        cfg_template_path = _DEFAULT_GNLSE_WDM_CONFIG
    if not nli_script_path.exists() or not cfg_template_path.exists():
        lg.warning(
            "SSFM disabled: missing gnlse resources. script={}, template={}",
            nli_script_path,
            cfg_template_path,
        )
        return None
    try:
        run_fn = _load_run_wdm_nli_simulation(nli_script_path)
        template_cfg = _toml_load(cfg_template_path)
        if not isinstance(template_cfg, dict):
            raise TypeError("Template TOML root is not a mapping")
    except Exception as exc:
        lg.warning("SSFM disabled: could not initialize gnlse runner ({})", exc)
        return None

    runtime_toml_path = Path(__file__).resolve().parents[2] / "input" / runtime_toml_name
    lg.info(
        "SSFM enabled via gnlse: script={}, template={}, runtime_toml={}",
        nli_script_path,
        cfg_template_path,
        runtime_toml_path,
    )
    return {
        "run_fn": run_fn,
        "template_cfg": template_cfg,
        "runtime_toml_path": runtime_toml_path,
        "out_dir": out_dir,
    }


def prepare_ssfm_runtime_with_template(
    out_dir: Path,
    template_path: Path | None,
    runtime_toml_name: str = "ssfm.toml",
) -> dict | None:
    nli_script_path = Path(str(Path.home() / "sw" / "gnlse-python" / "examples" / "nli" / "nli.py"))
    if not nli_script_path.exists():
        nli_script_path = _DEFAULT_GNLSE_NLI_PY

    if template_path is None:
        cfg_template_path = Path(str(Path.home() / "sw" / "gnlse-python" / "input" / "wdm_nli_config.toml"))
        if not cfg_template_path.exists():
            cfg_template_path = _DEFAULT_GNLSE_WDM_CONFIG
    else:
        cfg_template_path = Path(template_path)

    if not nli_script_path.exists() or not cfg_template_path.exists():
        lg.warning(
            "SSFM disabled: missing gnlse resources. script={}, template={}",
            nli_script_path,
            cfg_template_path,
        )
        return None
    try:
        run_fn = _load_run_wdm_nli_simulation(nli_script_path)
        template_cfg = _toml_load(cfg_template_path)
        if not isinstance(template_cfg, dict):
            raise TypeError("Template TOML root is not a mapping")
    except Exception as exc:
        lg.warning("SSFM disabled: could not initialize gnlse runner ({})", exc)
        return None

    runtime_toml_path = Path(__file__).resolve().parents[2] / "input" / runtime_toml_name
    lg.info(
        "SSFM enabled via gnlse: script={}, template={}, runtime_toml={}",
        nli_script_path,
        cfg_template_path,
        runtime_toml_path,
    )
    return {
        "run_fn": run_fn,
        "template_cfg": template_cfg,
        "runtime_toml_path": runtime_toml_path,
        "out_dir": out_dir,
    }


def compute_ssfm_center_nli(
    ssfm_ctx: dict,
    *,
    system: System,
    launch_channel_w: float,
    channel_idx: int,
    sweep_tag: str,
) -> float | None:
    runtime_cfg = _build_ssfm_runtime_config(
        template_cfg=ssfm_ctx["template_cfg"],
        system=system,
        launch_channel_w=launch_channel_w,
        channel_idx=channel_idx,
        out_dir=ssfm_ctx["out_dir"],
        sweep_tag=sweep_tag,
    )
    runtime_toml_path = Path(ssfm_ctx["runtime_toml_path"])
    _write_toml(runtime_toml_path, runtime_cfg, comments=_SSFM_TOML_HEADER)
    payload = ssfm_ctx["run_fn"](runtime_toml_path)
    return _extract_ssfm_center_nli_w(payload)
