[metadata]
name = pynlin
version = 0.0.0
description = PyNLIN
long_description = file: README.md
long_description_content_type = text/markdown

[options]
packages = find:
python_requires = >=3.9
include_package_data = False

[options.packages.find]
where = .
include =
    pynlin
    pynlin.*
    scripts
    scripts.*
exclude =
    tests*
    docs*
    examples*
    results*
    results_pre_cristian*
    media*
    logs*
    input*
    addons*
    additional*
