"""Canonical PCFM/GN method exports."""

from pynlin.methods.pcfm.gn import (
    MAX_POWER_W,
    MAX_SPP,
    MIN_BETA2,
    MIN_POWER_W,
    N2_SIO2,
    POLARIZATION_COUNT,
    PcfmConfig,
    _aeff_array,
    _beta2_eff,
    _beta2_array,
    _beta_coeffs_from_profile,
    _to_per_channel_power,
    _to_per_polarization_power,
    compute_gn_direct,
    compute_gn_numeric,
    compute_pcfm_nlin,
    compute_sci_numeric,
    compute_sci_numeric_direct,
    compute_xci_numeric,
    compute_xci_numeric_direct,
    fit_spp_polynomials,
    load_signal_profiles,
    normalize_spp,
    poly_eval,
    poly_sum,
)

__all__ = [
    "MAX_POWER_W",
    "MAX_SPP",
    "MIN_BETA2",
    "MIN_POWER_W",
    "N2_SIO2",
    "POLARIZATION_COUNT",
    "PcfmConfig",
    "_aeff_array",
    "_beta2_eff",
    "_beta2_array",
    "_beta_coeffs_from_profile",
    "_to_per_channel_power",
    "_to_per_polarization_power",
    "compute_gn_direct",
    "compute_gn_numeric",
    "compute_pcfm_nlin",
    "compute_sci_numeric",
    "compute_sci_numeric_direct",
    "compute_xci_numeric",
    "compute_xci_numeric_direct",
    "fit_spp_polynomials",
    "load_signal_profiles",
    "normalize_spp",
    "poly_eval",
    "poly_sum",
]
