import copy
from dataclasses import dataclass
import importlib.util
import json
from pathlib import Path
import subprocess
import sys

import numpy as np
from loguru import logger as lg
from scipy.constants import speed_of_light as c0

from pynlin.system import System
from pynlin.methods.td.fullband_mc import gamma_grid
from pynlin.utils import _toml_load

_DEFAULT_GNLSE_NLI_PY = Path("/home/lorenzi/sw/gnlse-python/examples/nli/nli.py")
_DEFAULT_GNLSE_WDM_CONFIG = Path("/home/lorenzi/sw/gnlse-python/input/wdm_nli_config.toml")

_SSFM_TOML_HEADER = [
    "Autogenerated runtime TOML for SSFM NLI evaluation from PyNLIN scaling scripts.",
    "This file is consumed by gnlse-python/examples/nli/nli.py::run_wdm_nli_simulation().",
    "Section names, field names, units and conventions follow the gnlse script/template exactly.",
    "Only scenario values are mapped from the current PyNLIN system (e.g., spacing, launch power, fiber parameters).",
    "The WDM channel count is intentionally forced to 5 for SSFM compatibility in this workflow.",
    "For the constant-profile comparison mode, fiber attenuation is set to zero so the SSFM run is lossless.",
    "The symbol rate follows the system baud rate; samples_per_symbol is recomputed per iteration.",
    "samples_per_symbol is set to the minimum integer that satisfies the Nyquist-band condition for the 5-channel plan.",
]


@dataclass(frozen=True)
class ScalarXPMN1Result:
    trial_seeds: np.ndarray
    full_nli_power_trials_w: np.ndarray
    cut_only_nli_power_trials_w: np.ndarray
    excess_power_trials_w: np.ndarray
    excess_power_mean_w: float
    excess_power_stderr_w: float
    n1_ssfm_m2: float
    n1_ssfm_stderr_m2: float
    gamma_w_inv_m: float
    full_payload: dict
    cut_only_payload: dict


@dataclass(frozen=True)
class ScalarXPMSweepFit:
    slope_w_inv: float
    slope_stderr_w_inv: float
    intercept_w: float
    r_squared: float
    n1_ssfm_m2: float
    n1_ssfm_stderr_m2: float
    mean_excess_power_w: np.ndarray
    mean_excess_power_stderr_w: np.ndarray


@dataclass(frozen=True)
class ScalarFWMExcessResult:
    trial_seeds: np.ndarray
    full_nli_power_trials_w: np.ndarray
    pump_control_nli_power_trials_w: np.ndarray
    source_control_nli_power_trials_w: np.ndarray
    idler_only_nli_power_trials_w: np.ndarray
    excess_power_trials_w: np.ndarray
    excess_power_mean_w: float
    excess_power_stderr_w: float
    c_ssfm_m2: float
    c_ssfm_stderr_m2: float
    gamma_w_inv_m: float
    full_payload: dict
    pump_control_payload: dict
    source_control_payload: dict
    idler_only_payload: dict


@dataclass(frozen=True)
class ScalarFWMSweepFit:
    slope_w_inv2: float
    slope_stderr_w_inv2: float
    intercept_w: float
    r_squared: float
    c_ssfm_m2: float
    c_ssfm_stderr_m2: float
    mean_excess_power_w: np.ndarray
    mean_excess_power_stderr_w: np.ndarray


def _toml_value_to_text(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, np.integer)):
        return str(int(value))
    if isinstance(value, (float, np.floating)):
        val = float(value)
        if not np.isfinite(val):
            raise ValueError(f"Cannot serialize non-finite float to TOML: {val}")
        return f"{val:.12g}"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value_to_text(v) for v in value) + "]"
    raise TypeError(f"Unsupported TOML value type: {type(value)!r}")


def _toml_dict_to_lines(data: dict, section: tuple[str, ...] = ()) -> list[str]:
    lines: list[str] = []
    scalar_items: list[tuple[str, object]] = []
    child_items: list[tuple[str, dict]] = []
    for key, value in data.items():
        if isinstance(value, dict):
            child_items.append((key, value))
        else:
            scalar_items.append((key, value))

    if section:
        lines.append(f"[{'.'.join(section)}]")
    for key, value in scalar_items:
        lines.append(f"{key} = {_toml_value_to_text(value)}")
    if scalar_items and child_items:
        lines.append("")

    for idx, (key, child) in enumerate(child_items):
        lines.extend(_toml_dict_to_lines(child, section=section + (key,)))
        if idx < len(child_items) - 1:
            lines.append("")
    return lines


def _write_toml(path: Path, data: dict, comments: list[str] | None = None) -> None:
    lines = _toml_dict_to_lines(data)
    if comments:
        header = [f"# {line}" for line in comments]
        lines = header + [""] + lines
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _load_run_wdm_nli_simulation(nli_script_path: Path):
    repo_root = nli_script_path.resolve().parents[2]
    external_python = repo_root / ".venv" / "bin" / "python"
    if external_python.exists():
        marker = "__PYNLIN_SSFM_PAYLOAD__"

        def run_external(config_path: Path):
            code = (
                "import json,sys; "
                "from examples.nli.nli import run_wdm_nli_simulation; "
                "payload=run_wdm_nli_simulation(sys.argv[1]); "
                f"print('{marker}'+json.dumps(payload))"
            )
            completed = subprocess.run(
                [str(external_python), "-c", code, str(Path(config_path).resolve())],
                cwd=repo_root,
                text=True,
                capture_output=True,
                check=False,
            )
            if completed.returncode != 0:
                details = (completed.stderr or completed.stdout)[-4000:]
                raise RuntimeError(
                    f"External SSFM process failed with code {completed.returncode}:\n{details}"
                )
            marker_index = completed.stdout.rfind(marker)
            if marker_index < 0:
                raise RuntimeError("External SSFM process returned no JSON payload")
            return json.loads(completed.stdout[marker_index + len(marker):])

        return run_external

    module_name = "gnlse_examples_nli_runtime"
    module_dir = str(nli_script_path.parent)
    if module_dir not in sys.path:
        sys.path.insert(0, module_dir)
    spec = importlib.util.spec_from_file_location(module_name, nli_script_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Unable to import module from {nli_script_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    run_fn = getattr(module, "run_wdm_nli_simulation", None)
    if run_fn is None:
        raise AttributeError(f"run_wdm_nli_simulation not found in {nli_script_path}")
    return run_fn


def _safe_beta2_ps2_per_m(system: System, channel_idx: int) -> float:
    freqs = system.wdm.frequency_grid()
    try:
        _, beta2_grid = system.beta_grids(freqs)
        beta2_val = float(np.asarray(beta2_grid, dtype=float)[0, channel_idx])
    except Exception:
        beta2_val = float(getattr(system.fiber, "beta2", 0.0) or 0.0)
    return beta2_val * 1e24


def _compute_min_samples_per_symbol_for_nyquist(
    *,
    symbol_rate_gbd: float,
    channel_spacing_thz: float,
    n_channels: int,
    pulse_shape: str,
    rrc_rolloff: float,
) -> int:
    symbol_rate_thz = float(symbol_rate_gbd) * 1e-3
    if symbol_rate_thz <= 0.0:
        raise ValueError("symbol_rate_gbd must be positive")
    max_offset_thz = channel_spacing_thz * (n_channels - 1) / 2.0
    if pulse_shape == "rrc":
        effective_bw_factor = 1.0 + float(rrc_rolloff)
    else:
        effective_bw_factor = 1.0
    rhs = (2.0 * max_offset_thz / symbol_rate_thz) + effective_bw_factor
    return max(int(np.ceil(rhs)), 2)


def _build_ssfm_runtime_config(
    *,
    template_cfg: dict,
    system: System,
    launch_channel_w: float,
    channel_idx: int,
    out_dir: Path,
    sweep_tag: str,
) -> dict:
    cfg = copy.deepcopy(template_cfg)
    mod = cfg.setdefault("modulation", {})
    mod.setdefault("order", 16)
    mod.setdefault("pulse_shape", "nyquist_rect")
    mod.setdefault("rrc_rolloff", 0.0)
    mod.setdefault("rrc_span_symbols", 12)
    mod.setdefault("n_symbols", 4096)
    pulse_shape = str(mod.get("pulse_shape", "nyquist_rect"))
    rrc_rolloff = float(mod.get("rrc_rolloff", 0.0))
    
    # Preserve symbol_rate_gbd from template if available; otherwise use system baud rate
    if "symbol_rate_gbd" not in mod:
        mod["symbol_rate_gbd"] = float(system.pulse.baud_rate * 1e-9)

    wdm = cfg.setdefault("wdm", {})
    wdm["n_channels"] = 5
    spacing = float(system.channel_spacing) if system.channel_spacing is not None else float(np.mean(np.diff(system.wdm.frequency_grid())))
    wdm["channel_spacing_thz"] = float(spacing * 1e-12)

    power_single_pol_w = float(launch_channel_w)
    power_dual_pol_w = power_single_pol_w * 2.0
    lg.warning(
        "SSFM power conversion: single-pol {:.6e} W -> dual-pol {:.6e} W",
        power_single_pol_w,
        power_dual_pol_w,
    )

    if "power_per_channel_w" not in wdm:
        wdm["power_per_channel_w"] = power_dual_pol_w

    mod["samples_per_symbol"] = _compute_min_samples_per_symbol_for_nyquist(
        symbol_rate_gbd=float(mod["symbol_rate_gbd"]),
        channel_spacing_thz=float(wdm["channel_spacing_thz"]),
        n_channels=int(wdm["n_channels"]),
        pulse_shape=pulse_shape,
        rrc_rolloff=rrc_rolloff,
    )

    freqs = system.wdm.frequency_grid()
    center_freq = float(freqs[channel_idx])
    fiber = cfg.setdefault("fiber", {})
    fiber["wavelength_nm"] = float((c0 / center_freq) * 1e9)
    fiber["fiber_length_m"] = float(system.fiber_length)

    gamma_raw = float(gamma_grid(system, np.asarray([center_freq], dtype=float))[0])
    gamma_scaled = gamma_raw * (8.0 / 9.0)
    fiber["nonlinearity"] = gamma_scaled
    lg.warning(
        "SSFM gamma conversion: single-pol {:.6e} -> dual-pol {:.6e} W⁻¹m⁻¹",
        gamma_raw,
        gamma_scaled,
    )

    fiber["loss_db_per_m"] = 0.0
    fiber["betas"] = [float(_safe_beta2_ps2_per_m(system, channel_idx))]

    output = cfg.setdefault("output", {})
    output["save_dir"] = str(out_dir / "ssfm")
    output["save_name"] = f"ssfm_constellation_{sweep_tag}.png"
    output["show_plot"] = False

    cache = cfg.setdefault("cache", {})
    cache.setdefault("mode", "recompute")

    monte_carlo = cfg.setdefault("monte_carlo", {})
    monte_carlo.setdefault("n_trials", 1)
    monte_carlo.setdefault("rng_seed", 1234)

    solver = cfg.setdefault("solver", {})
    solver.setdefault("z_saves", 2)
    solver.setdefault("rtol", 1e-5)
    solver.setdefault("atol", 1e-7)
    solver.setdefault("ssfm_max_nonlinear_phase_deg", 0.02)
    solver.setdefault("ssfm_max_step_m", 1000)
    solver.setdefault("propagation_backend", "gnlse")
    return cfg


def _build_scalar_xpm_runtime_config(
    *,
    template_cfg: dict,
    system: System,
    cut_power_w: float,
    interferer_power_w: float,
    channel_idx: int,
    interferer_idx: int,
    out_dir: Path,
    scenario_tag: str,
    n_trials: int,
    rng_seed: int,
    n_symbols: int,
    samples_per_symbol: int,
    max_step_m: float,
    max_nonlinear_phase_deg: float,
    fiber_length_m: float | None = None,
    target_frequency_hz: float | None = None,
    interferer_frequency_hz: float | None = None,
    dispersion_betas_ps_per_m: list[float] | None = None,
    save_plots: bool = False,
    symbol_distribution: str = "circular_complex_gaussian",
) -> dict:
    """Build a scalar, lossless three-slot XPM configuration."""
    if channel_idx == interferer_idx:
        raise ValueError("CUT and interferer indices must differ")
    if cut_power_w <= 0.0 or interferer_power_w < 0.0:
        raise ValueError("CUT power must be positive and interferer power non-negative")
    if symbol_distribution not in {"qam", "circular_complex_gaussian"}:
        raise ValueError(
            "symbol_distribution must be 'qam' or 'circular_complex_gaussian'"
        )

    cfg = copy.deepcopy(template_cfg)
    mod = cfg.setdefault("modulation", {})
    mod.update({
        "order": 16,
        "symbol_distribution": str(symbol_distribution),
        "symbol_rate_gbd": float(system.pulse.baud_rate * 1e-9),
        "pulse_shape": "nyquist_rect",
        "rrc_rolloff": 0.0,
        "rrc_span_symbols": 12,
        "n_symbols": int(n_symbols),
    })

    freqs = np.asarray(system.wdm.frequency_grid(), dtype=float)
    has_virtual_frequencies = (
        target_frequency_hz is not None or interferer_frequency_hz is not None
    )
    if has_virtual_frequencies:
        if target_frequency_hz is None or interferer_frequency_hz is None:
            raise ValueError("target and interferer frequencies must be provided together")
        center_freq = float(target_frequency_hz)
        interferer_freq = float(interferer_frequency_hz)
    else:
        center_freq = float(freqs[channel_idx])
        interferer_freq = float(freqs[interferer_idx])
    spacing_hz = abs(interferer_freq - center_freq)
    min_sps = _compute_min_samples_per_symbol_for_nyquist(
        symbol_rate_gbd=float(mod["symbol_rate_gbd"]),
        channel_spacing_thz=spacing_hz * 1e-12,
        n_channels=3,
        pulse_shape="nyquist_rect",
        rrc_rolloff=0.0,
    )
    mod["samples_per_symbol"] = max(int(samples_per_symbol), min_sps)

    powers = [0.0, float(cut_power_w), 0.0]
    powers[0 if interferer_freq < center_freq else 2] = float(interferer_power_w)
    wdm = cfg.setdefault("wdm", {})
    wdm.pop("power_per_channel_w", None)
    wdm.update({
        "n_channels": 3,
        "channel_spacing_thz": spacing_hz * 1e-12,
        "channel_powers_w": powers,
    })

    gamma = float(gamma_grid(system, np.asarray([center_freq], dtype=float))[0])
    betas = (
        [float(_safe_beta2_ps2_per_m(system, channel_idx))]
        if dispersion_betas_ps_per_m is None
        else [float(value) for value in dispersion_betas_ps_per_m]
    )
    fiber = cfg.setdefault("fiber", {})
    fiber.update({
        "wavelength_nm": float((c0 / center_freq) * 1e9),
        "fiber_length_m": float(
            system.fiber_length if fiber_length_m is None else fiber_length_m
        ),
        "nonlinearity": gamma,
        "loss_db_per_m": 0.0,
        "betas": betas,
    })

    cfg.setdefault("monte_carlo", {}).update({
        "n_trials": int(n_trials),
        "rng_seed": int(rng_seed),
    })
    cfg.setdefault("solver", {}).update({
        "z_saves": 2,
        "rtol": 1e-6,
        "atol": 1e-8,
        "ssfm_max_nonlinear_phase_deg": float(max_nonlinear_phase_deg),
        "ssfm_max_step_m": float(max_step_m),
        "propagation_backend": "custom_ssfm",
    })
    cfg.setdefault("output", {}).update({
        "save_dir": str(Path(out_dir) / "ssfm" / scenario_tag),
        "save_name": f"{scenario_tag}.png",
        "show_plot": False,
        "save_plots": bool(save_plots),
    })
    cfg.setdefault("cache", {})["mode"] = "recompute"
    return cfg


def _paired_trial_powers(full_payload: dict, cut_payload: dict) -> tuple[np.ndarray, ...]:
    try:
        full_trials = full_payload["trial_results"]["trials"]
        cut_trials = cut_payload["trial_results"]["trials"]
    except (KeyError, TypeError) as exc:
        raise ValueError("SSFM payload lacks schema-v2 per-trial records") from exc
    if len(full_trials) != len(cut_trials) or not full_trials:
        raise ValueError("SSFM full/control trial counts do not match")

    seeds = []
    full_power = []
    cut_power = []
    for full, cut in zip(full_trials, cut_trials):
        if full["seed"] != cut["seed"]:
            raise ValueError("SSFM full/control trial seeds do not match")
        if full["cut_tx_symbol_sha256"] != cut["cut_tx_symbol_sha256"]:
            raise ValueError("SSFM full/control CUT symbols do not match")
        if full["n_symbols_used"] != cut["n_symbols_used"]:
            raise ValueError("SSFM full/control receiver symbol counts do not match")
        seeds.append(int(full["seed"]))
        full_power.append(float(full["center_nli_power_w"]))
        cut_power.append(float(cut["center_nli_power_w"]))

    arrays = tuple(np.asarray(values) for values in (seeds, full_power, cut_power))
    if not all(np.all(np.isfinite(values)) for values in arrays):
        raise ValueError("SSFM per-trial records contain non-finite values")
    return arrays


def compute_scalar_ssfm_xpm_n1(
    ssfm_ctx: dict,
    *,
    system: System,
    cut_power_w: float,
    interferer_power_w: float,
    channel_idx: int,
    interferer_idx: int,
    n_trials: int,
    rng_seed: int,
    sweep_tag: str,
    n_symbols: int = 4096,
    samples_per_symbol: int = 16,
    max_step_m: float = 1000.0,
    max_nonlinear_phase_deg: float = 0.05,
    fiber_length_m: float | None = None,
    target_frequency_hz: float | None = None,
    interferer_frequency_hz: float | None = None,
    dispersion_betas_ps_per_m: list[float] | None = None,
    save_full_plots: bool = False,
    symbol_distribution: str = "circular_complex_gaussian",
) -> ScalarXPMN1Result:
    """Run paired scalar SSFM cases and infer prefactor-free XPM N1."""
    common = dict(
        template_cfg=ssfm_ctx["template_cfg"],
        system=system,
        cut_power_w=cut_power_w,
        channel_idx=channel_idx,
        interferer_idx=interferer_idx,
        out_dir=Path(ssfm_ctx["out_dir"]),
        n_trials=n_trials,
        rng_seed=rng_seed,
        n_symbols=n_symbols,
        samples_per_symbol=samples_per_symbol,
        max_step_m=max_step_m,
        max_nonlinear_phase_deg=max_nonlinear_phase_deg,
        fiber_length_m=fiber_length_m,
        target_frequency_hz=target_frequency_hz,
        interferer_frequency_hz=interferer_frequency_hz,
        dispersion_betas_ps_per_m=dispersion_betas_ps_per_m,
        symbol_distribution=symbol_distribution,
    )
    full_cfg = _build_scalar_xpm_runtime_config(
        **common,
        interferer_power_w=interferer_power_w,
        scenario_tag=f"{sweep_tag}_full",
        save_plots=save_full_plots,
    )
    cut_cfg = _build_scalar_xpm_runtime_config(
        **common,
        interferer_power_w=0.0,
        scenario_tag=f"{sweep_tag}_cut_only",
        save_plots=False,
    )

    runtime_dir = Path(ssfm_ctx["out_dir"]) / "ssfm" / "runtime"
    full_path = runtime_dir / f"{sweep_tag}_full.toml"
    cut_path = runtime_dir / f"{sweep_tag}_cut_only.toml"
    _write_toml(full_path, full_cfg, comments=_SSFM_TOML_HEADER)
    _write_toml(cut_path, cut_cfg, comments=_SSFM_TOML_HEADER)
    full_payload = ssfm_ctx["run_fn"](full_path)
    cut_payload = ssfm_ctx["run_fn"](cut_path)

    seeds, full_power, cut_power = _paired_trial_powers(full_payload, cut_payload)
    excess = full_power - cut_power
    excess_mean = float(np.mean(excess))
    excess_stderr = (
        float(np.std(excess, ddof=1) / np.sqrt(excess.size))
        if excess.size > 1 else 0.0
    )
    center_freq = (
        float(np.asarray(system.wdm.frequency_grid())[channel_idx])
        if target_frequency_hz is None
        else float(target_frequency_hz)
    )
    gamma = float(gamma_grid(system, np.asarray([center_freq]))[0])
    denominator = 4.0 * gamma**2 * float(cut_power_w) * float(interferer_power_w)**2
    if denominator <= 0.0:
        raise ValueError("The N1 normalization requires a positive interferer power")

    return ScalarXPMN1Result(
        trial_seeds=seeds.astype(int),
        full_nli_power_trials_w=full_power,
        cut_only_nli_power_trials_w=cut_power,
        excess_power_trials_w=excess,
        excess_power_mean_w=excess_mean,
        excess_power_stderr_w=excess_stderr,
        n1_ssfm_m2=excess_mean / denominator,
        n1_ssfm_stderr_m2=excess_stderr / denominator,
        gamma_w_inv_m=gamma,
        full_payload=full_payload,
        cut_only_payload=cut_payload,
    )


def fit_scalar_ssfm_xpm_sweep(
    results: list[ScalarXPMN1Result],
    interferer_powers_w: np.ndarray,
    *,
    cut_power_w: float,
) -> ScalarXPMSweepFit:
    """Fit paired SSFM excess powers against interferer power squared."""
    powers = np.asarray(interferer_powers_w, dtype=float)
    if len(results) != powers.size or powers.size < 2:
        raise ValueError("results and at least two interferer powers must match")
    excess = np.stack([result.excess_power_trials_w for result in results])
    if len({row.size for row in excess}) != 1:
        raise ValueError("all SSFM sweep points must have the same trial count")
    power_squared = powers**2
    slopes = np.empty(excess.shape[1])
    intercepts = np.empty(excess.shape[1])
    for trial in range(excess.shape[1]):
        slopes[trial], intercepts[trial] = np.polyfit(
            power_squared, excess[:, trial], deg=1
        )
    slope = float(np.mean(slopes))
    slope_stderr = (
        float(np.std(slopes, ddof=1) / np.sqrt(slopes.size))
        if slopes.size > 1 else 0.0
    )
    gamma = float(results[0].gamma_w_inv_m)
    if not all(np.isclose(result.gamma_w_inv_m, gamma) for result in results):
        raise ValueError("gamma changed within one SSFM power sweep")
    denominator = 4.0 * gamma**2 * float(cut_power_w)
    mean_excess = np.mean(excess, axis=1)
    mean_intercept = float(np.mean(intercepts))
    fitted = slope * power_squared + mean_intercept
    residual_sum = float(np.sum((mean_excess - fitted) ** 2))
    total_sum = float(np.sum((mean_excess - np.mean(mean_excess)) ** 2))
    r_squared = 1.0 - residual_sum / total_sum if total_sum > 0.0 else float("nan")
    point_stderr = (
        np.std(excess, axis=1, ddof=1) / np.sqrt(excess.shape[1])
        if excess.shape[1] > 1 else np.zeros(powers.size)
    )
    return ScalarXPMSweepFit(
        slope_w_inv=slope,
        slope_stderr_w_inv=slope_stderr,
        intercept_w=mean_intercept,
        r_squared=r_squared,
        n1_ssfm_m2=slope / denominator,
        n1_ssfm_stderr_m2=slope_stderr / denominator,
        mean_excess_power_w=mean_excess,
        mean_excess_power_stderr_w=point_stderr,
    )


def _build_scalar_fwm_runtime_config(
    *,
    template_cfg: dict,
    system: System,
    idler_power_w: float,
    pump_power_w: float,
    source_power_w: float,
    target_frequency_hz: float,
    spacing_hz: float,
    out_dir: Path,
    scenario_tag: str,
    n_trials: int,
    rng_seed: int,
    n_symbols: int,
    samples_per_symbol: int,
    max_step_m: float,
    max_nonlinear_phase_deg: float,
    fiber_length_m: float | None = None,
    dispersion_betas_ps_per_m: list[float] | None = None,
    save_plots: bool = False,
    symbol_distribution: str = "circular_complex_gaussian",
) -> dict:
    """Build a scalar, lossless five-slot degenerate-FWM configuration.

    The idler/CUT sits on the center slot, the pump one spacing above, and the
    source two spacings above, so the degenerate product 2*f_pump - f_source
    lands exactly on the idler. The two slots below the idler stay dark.
    """
    if idler_power_w <= 0.0:
        raise ValueError("The idler power must be positive (receiver center channel)")
    if pump_power_w < 0.0 or source_power_w < 0.0:
        raise ValueError("Pump and source powers must be non-negative")
    if spacing_hz <= 0.0:
        raise ValueError("The pump/source spacing must be positive")
    if symbol_distribution not in {"qam", "circular_complex_gaussian"}:
        raise ValueError(
            "symbol_distribution must be 'qam' or 'circular_complex_gaussian'"
        )

    cfg = copy.deepcopy(template_cfg)
    mod = cfg.setdefault("modulation", {})
    mod.update({
        "order": 16,
        "symbol_distribution": str(symbol_distribution),
        "symbol_rate_gbd": float(system.pulse.baud_rate * 1e-9),
        "pulse_shape": "nyquist_rect",
        "rrc_rolloff": 0.0,
        "rrc_span_symbols": 12,
        "n_symbols": int(n_symbols),
    })
    min_sps = _compute_min_samples_per_symbol_for_nyquist(
        symbol_rate_gbd=float(mod["symbol_rate_gbd"]),
        channel_spacing_thz=float(spacing_hz) * 1e-12,
        n_channels=5,
        pulse_shape="nyquist_rect",
        rrc_rolloff=0.0,
    )
    mod["samples_per_symbol"] = max(int(samples_per_symbol), min_sps)

    wdm = cfg.setdefault("wdm", {})
    wdm.pop("power_per_channel_w", None)
    wdm.update({
        "n_channels": 5,
        "channel_spacing_thz": float(spacing_hz) * 1e-12,
        "channel_powers_w": [
            0.0,
            0.0,
            float(idler_power_w),
            float(pump_power_w),
            float(source_power_w),
        ],
    })

    center_freq = float(target_frequency_hz)
    gamma = float(gamma_grid(system, np.asarray([center_freq], dtype=float))[0])
    if dispersion_betas_ps_per_m is None:
        raise ValueError("The FWM configuration requires explicit dispersion betas")
    fiber = cfg.setdefault("fiber", {})
    fiber.update({
        "wavelength_nm": float((c0 / center_freq) * 1e9),
        "fiber_length_m": float(
            system.fiber_length if fiber_length_m is None else fiber_length_m
        ),
        "nonlinearity": gamma,
        "loss_db_per_m": 0.0,
        "betas": [float(value) for value in dispersion_betas_ps_per_m],
    })

    cfg.setdefault("monte_carlo", {}).update({
        "n_trials": int(n_trials),
        "rng_seed": int(rng_seed),
    })
    cfg.setdefault("solver", {}).update({
        "z_saves": 2,
        "rtol": 1e-6,
        "atol": 1e-8,
        "ssfm_max_nonlinear_phase_deg": float(max_nonlinear_phase_deg),
        "ssfm_max_step_m": float(max_step_m),
        "propagation_backend": "custom_ssfm",
    })
    cfg.setdefault("output", {}).update({
        "save_dir": str(Path(out_dir) / "ssfm" / scenario_tag),
        "save_name": f"{scenario_tag}.png",
        "show_plot": False,
        "save_plots": bool(save_plots),
    })
    cfg.setdefault("cache", {})["mode"] = "recompute"
    return cfg


def compute_scalar_ssfm_fwm_excess(
    ssfm_ctx: dict,
    *,
    system: System,
    idler_power_w: float,
    pump_power_w: float,
    source_power_w: float,
    target_frequency_hz: float,
    spacing_hz: float,
    n_trials: int,
    rng_seed: int,
    sweep_tag: str,
    n_symbols: int = 2048,
    samples_per_symbol: int = 8,
    max_step_m: float = 500.0,
    max_nonlinear_phase_deg: float = 0.05,
    fiber_length_m: float | None = None,
    dispersion_betas_ps_per_m: list[float] | None = None,
    idler_only_payload: dict | None = None,
    save_full_plots: bool = False,
    symbol_distribution: str = "circular_complex_gaussian",
) -> ScalarFWMExcessResult:
    """Isolate the degenerate FWM power via four seed-paired scalar SSFM runs.

    The inclusion-exclusion
    ``full - pump_control - source_control + idler_only``
    cancels SCI and both XPM terms at first order, leaving the FWM excess.
    A precomputed ``idler_only_payload`` (power-sweep invariant) is reused
    across sweep points instead of rerunning the idler-only case.
    """
    if pump_power_w <= 0.0 or source_power_w <= 0.0:
        raise ValueError("Pump and source powers must be positive for the full case")
    common = dict(
        template_cfg=ssfm_ctx["template_cfg"],
        system=system,
        idler_power_w=idler_power_w,
        target_frequency_hz=target_frequency_hz,
        spacing_hz=spacing_hz,
        out_dir=Path(ssfm_ctx["out_dir"]),
        n_trials=n_trials,
        rng_seed=rng_seed,
        n_symbols=n_symbols,
        samples_per_symbol=samples_per_symbol,
        max_step_m=max_step_m,
        max_nonlinear_phase_deg=max_nonlinear_phase_deg,
        fiber_length_m=fiber_length_m,
        dispersion_betas_ps_per_m=dispersion_betas_ps_per_m,
        symbol_distribution=symbol_distribution,
    )
    cases = {
        "full": dict(
            pump_power_w=pump_power_w,
            source_power_w=source_power_w,
            save_plots=save_full_plots,
        ),
        "pump_control": dict(
            pump_power_w=pump_power_w, source_power_w=0.0, save_plots=False
        ),
        "source_control": dict(
            pump_power_w=0.0, source_power_w=source_power_w, save_plots=False
        ),
        "idler_only": dict(pump_power_w=0.0, source_power_w=0.0, save_plots=False),
    }
    runtime_dir = Path(ssfm_ctx["out_dir"]) / "ssfm" / "runtime"
    payloads: dict[str, dict] = {}
    for case, overrides in cases.items():
        if case == "idler_only" and idler_only_payload is not None:
            payloads[case] = idler_only_payload
            continue
        cfg = _build_scalar_fwm_runtime_config(
            **common, scenario_tag=f"{sweep_tag}_{case}", **overrides
        )
        path = runtime_dir / f"{sweep_tag}_{case}.toml"
        _write_toml(path, cfg, comments=_SSFM_TOML_HEADER)
        payloads[case] = ssfm_ctx["run_fn"](path)

    seeds, full_power, pump_power = _paired_trial_powers(
        payloads["full"], payloads["pump_control"]
    )
    _, _, source_power = _paired_trial_powers(
        payloads["full"], payloads["source_control"]
    )
    _, _, idler_power = _paired_trial_powers(
        payloads["full"], payloads["idler_only"]
    )
    excess = full_power - pump_power - source_power + idler_power
    excess_mean = float(np.mean(excess))
    excess_stderr = (
        float(np.std(excess, ddof=1) / np.sqrt(excess.size))
        if excess.size > 1 else 0.0
    )
    gamma = float(gamma_grid(system, np.asarray([float(target_frequency_hz)]))[0])
    denominator = 2.0 * gamma**2 * float(pump_power_w) ** 2 * float(source_power_w)

    return ScalarFWMExcessResult(
        trial_seeds=seeds.astype(int),
        full_nli_power_trials_w=full_power,
        pump_control_nli_power_trials_w=pump_power,
        source_control_nli_power_trials_w=source_power,
        idler_only_nli_power_trials_w=idler_power,
        excess_power_trials_w=excess,
        excess_power_mean_w=excess_mean,
        excess_power_stderr_w=excess_stderr,
        c_ssfm_m2=excess_mean / denominator,
        c_ssfm_stderr_m2=excess_stderr / denominator,
        gamma_w_inv_m=gamma,
        full_payload=payloads["full"],
        pump_control_payload=payloads["pump_control"],
        source_control_payload=payloads["source_control"],
        idler_only_payload=payloads["idler_only"],
    )


def fit_scalar_ssfm_fwm_sweep(
    results: list[ScalarFWMExcessResult],
    pump_powers_w: np.ndarray,
    source_powers_w: np.ndarray,
) -> ScalarFWMSweepFit:
    """Fit paired FWM excess powers against the cubic term P_pump^2 * P_source."""
    pump_powers = np.asarray(pump_powers_w, dtype=float)
    source_powers = np.asarray(source_powers_w, dtype=float)
    if len(results) != pump_powers.size or pump_powers.size != source_powers.size:
        raise ValueError("results, pump powers, and source powers must align")
    if pump_powers.size < 2:
        raise ValueError("at least two sweep points are required")
    excess = np.stack([result.excess_power_trials_w for result in results])
    if len({row.size for row in excess}) != 1:
        raise ValueError("all SSFM sweep points must have the same trial count")
    power_cubed = pump_powers**2 * source_powers
    if np.unique(power_cubed).size != power_cubed.size:
        raise ValueError("sweep points must have distinct P_pump^2 * P_source values")
    slopes = np.empty(excess.shape[1])
    intercepts = np.empty(excess.shape[1])
    for trial in range(excess.shape[1]):
        slopes[trial], intercepts[trial] = np.polyfit(
            power_cubed, excess[:, trial], deg=1
        )
    slope = float(np.mean(slopes))
    slope_stderr = (
        float(np.std(slopes, ddof=1) / np.sqrt(slopes.size))
        if slopes.size > 1 else 0.0
    )
    gamma = float(results[0].gamma_w_inv_m)
    if not all(np.isclose(result.gamma_w_inv_m, gamma) for result in results):
        raise ValueError("gamma changed within one SSFM power sweep")
    denominator = 2.0 * gamma**2
    mean_excess = np.mean(excess, axis=1)
    mean_intercept = float(np.mean(intercepts))
    fitted = slope * power_cubed + mean_intercept
    residual_sum = float(np.sum((mean_excess - fitted) ** 2))
    total_sum = float(np.sum((mean_excess - np.mean(mean_excess)) ** 2))
    r_squared = 1.0 - residual_sum / total_sum if total_sum > 0.0 else float("nan")
    point_stderr = (
        np.std(excess, axis=1, ddof=1) / np.sqrt(excess.shape[1])
        if excess.shape[1] > 1 else np.zeros(pump_powers.size)
    )
    return ScalarFWMSweepFit(
        slope_w_inv2=slope,
        slope_stderr_w_inv2=slope_stderr,
        intercept_w=mean_intercept,
        r_squared=r_squared,
        c_ssfm_m2=slope / denominator,
        c_ssfm_stderr_m2=slope_stderr / denominator,
        mean_excess_power_w=mean_excess,
        mean_excess_power_stderr_w=point_stderr,
    )


def _extract_ssfm_center_nli_w(payload: dict) -> float | None:
    try:
        value = payload["power_report"]["center_channel"]["nli_power_avg_w"]
        if value is None:
            return None
        out_dual_pol = float(value)
        if not np.isfinite(out_dual_pol):
            return None
        out_single_pol = out_dual_pol / 2.0
        lg.warning(
            "SSFM output conversion: dual-pol {:.6e} W -> single-pol {:.6e} W",
            out_dual_pol,
            out_single_pol,
        )
        return out_single_pol
    except Exception:
        return None


def prepare_ssfm_runtime(out_dir: Path, runtime_toml_name: str = "ssfm.toml") -> dict | None:
    nli_script_path = Path(str(Path.home() / "sw" / "gnlse-python" / "examples" / "nli" / "nli.py"))
    cfg_template_path = Path(str(Path.home() / "sw" / "gnlse-python" / "input" / "wdm_nli_config.toml"))
    if not nli_script_path.exists():
        nli_script_path = _DEFAULT_GNLSE_NLI_PY
    if not cfg_template_path.exists():
        cfg_template_path = _DEFAULT_GNLSE_WDM_CONFIG
    if not nli_script_path.exists() or not cfg_template_path.exists():
        lg.warning(
            f"SSFM disabled: missing gnlse resources. script={nli_script_path}, "
            f"template={cfg_template_path}"
        )
        return None
    try:
        run_fn = _load_run_wdm_nli_simulation(nli_script_path)
        template_cfg = _toml_load(cfg_template_path)
        if not isinstance(template_cfg, dict):
            raise TypeError("Template TOML root is not a mapping")
    except Exception as exc:
        lg.warning(f"SSFM disabled: could not initialize gnlse runner ({exc})")
        return None

    runtime_toml_path = Path(out_dir) / "ssfm" / "runtime" / runtime_toml_name
    lg.info(
        f"SSFM enabled via gnlse: script={nli_script_path}, "
        f"template={cfg_template_path}, runtime_toml={runtime_toml_path}"
    )
    return {
        "run_fn": run_fn,
        "template_cfg": template_cfg,
        "runtime_toml_path": runtime_toml_path,
        "out_dir": out_dir,
    }


def prepare_ssfm_runtime_with_template(
    out_dir: Path,
    template_path: Path | None,
    runtime_toml_name: str = "ssfm.toml",
) -> dict | None:
    nli_script_path = Path(str(Path.home() / "sw" / "gnlse-python" / "examples" / "nli" / "nli.py"))
    if not nli_script_path.exists():
        nli_script_path = _DEFAULT_GNLSE_NLI_PY

    if template_path is None:
        cfg_template_path = Path(str(Path.home() / "sw" / "gnlse-python" / "input" / "wdm_nli_config.toml"))
        if not cfg_template_path.exists():
            cfg_template_path = _DEFAULT_GNLSE_WDM_CONFIG
    else:
        cfg_template_path = Path(template_path)

    if not nli_script_path.exists() or not cfg_template_path.exists():
        lg.warning(
            f"SSFM disabled: missing gnlse resources. script={nli_script_path}, "
            f"template={cfg_template_path}"
        )
        return None
    try:
        run_fn = _load_run_wdm_nli_simulation(nli_script_path)
        template_cfg = _toml_load(cfg_template_path)
        if not isinstance(template_cfg, dict):
            raise TypeError("Template TOML root is not a mapping")
    except Exception as exc:
        lg.warning(f"SSFM disabled: could not initialize gnlse runner ({exc})")
        return None

    runtime_toml_path = Path(out_dir) / "ssfm" / "runtime" / runtime_toml_name
    lg.info(
        f"SSFM enabled via gnlse: script={nli_script_path}, "
        f"template={cfg_template_path}, runtime_toml={runtime_toml_path}"
    )
    return {
        "run_fn": run_fn,
        "template_cfg": template_cfg,
        "runtime_toml_path": runtime_toml_path,
        "out_dir": out_dir,
    }


def compute_ssfm_center_nli(
    ssfm_ctx: dict,
    *,
    system: System,
    launch_channel_w: float,
    channel_idx: int,
    sweep_tag: str,
) -> float | None:
    runtime_cfg = _build_ssfm_runtime_config(
        template_cfg=ssfm_ctx["template_cfg"],
        system=system,
        launch_channel_w=launch_channel_w,
        channel_idx=channel_idx,
        out_dir=ssfm_ctx["out_dir"],
        sweep_tag=sweep_tag,
    )
    runtime_toml_path = Path(ssfm_ctx["runtime_toml_path"])
    _write_toml(runtime_toml_path, runtime_cfg, comments=_SSFM_TOML_HEADER)
    payload = ssfm_ctx["run_fn"](runtime_toml_path)
    return _extract_ssfm_center_nli_w(payload)
