import argparse
import copy
import importlib.util
from pathlib import Path
import sys

import matplotlib
import numpy as np
from loguru import logger as lg
from matplotlib.ticker import ScalarFormatter
from scipy.constants import speed_of_light as c0

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from pynlin.constellation_stats import gaussian_mu0
from pynlin.nlin.nlin_estimator_uwb import collision_coeffs_system_uwb, total_nlin_uwb
from pynlin.nlin.pcfm_gn import PcfmConfig
from pynlin.system import System
from pynlin.utils import _toml_load, dBm2watt, watt2dBm

from analysis.pcfm.config import (
    _format_scaling_plot_title,
    _load_pcfm_runtime_config,
    _resolve_scaling_run_flags,
    _select_scaling_channel,
)
from analysis.pcfm.analytics import pcfm_general
from analysis.pcfm.figure_size import scale_figsize_to_ieee_column
from analysis.pcfm.io import (
    _launch_referenced_nlin_to_output_power,
    _output_over_launch_signal_power_ratio,
    _power_profile_hash,
    _resolve_launch_powers,
    _write_flat_profile,
)
from analysis.pcfm.models import _load_or_compute_pcfm_I
from analysis.pcfm.td import _td_modulation_components
from analysis.uwb_nlin import _nlin_cache_path

plt.rcParams["text.usetex"] = False

_DEFAULT_GNLSE_NLI_PY = Path("/home/lorenzi/sw/gnlse-python/examples/nli/nli.py")
_DEFAULT_GNLSE_WDM_CONFIG = Path("/home/lorenzi/sw/gnlse-python/input/wdm_nli_config.toml")
_SSFM_RUNTIME_TOML_NAME = "ssfm.toml"
_SSFM_TOML_HEADER = [
    "Autogenerated runtime TOML for SSFM NLI evaluation inside pcfm_baud_scaling.",
    "This file is consumed by gnlse-python/examples/nli/nli.py::run_wdm_nli_simulation().",
    "Section names, field names, units and conventions follow the gnlse script/template exactly.",
    "Only scenario values are mapped from the current PCFM system (e.g., baud rate, spacing, launch power, fiber parameters).",
    "The WDM channel count is intentionally forced to 5 for SSFM compatibility in this workflow.",
    "For the constant-profile comparison mode, fiber attenuation is set to zero so the SSFM run is lossless.",
    "The symbol rate follows the swept baud rate; samples_per_symbol is recomputed per iteration.",
    "samples_per_symbol is set to the minimum integer that satisfies the Nyquist-band condition for the 5-channel plan.",
]

def _toml_value_to_text(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, np.integer)):
        return str(int(value))
    if isinstance(value, (float, np.floating)):
        val = float(value)
        if not np.isfinite(val):
            raise ValueError(f"Cannot serialize non-finite float to TOML: {val}")
        return f"{val:.12g}"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value_to_text(v) for v in value) + "]"
    raise TypeError(f"Unsupported TOML value type: {type(value)!r}")


def _toml_dict_to_lines(data: dict, section: tuple[str, ...] = ()) -> list[str]:
    lines: list[str] = []
    scalar_items: list[tuple[str, object]] = []
    child_items: list[tuple[str, dict]] = []
    for key, value in data.items():
        if isinstance(value, dict):
            child_items.append((key, value))
        else:
            scalar_items.append((key, value))

    if section:
        lines.append(f"[{'.'.join(section)}]")
    for key, value in scalar_items:
        lines.append(f"{key} = {_toml_value_to_text(value)}")
    if scalar_items and child_items:
        lines.append("")

    for idx, (key, child) in enumerate(child_items):
        lines.extend(_toml_dict_to_lines(child, section=section + (key,)))
        if idx < len(child_items) - 1:
            lines.append("")
    return lines


def _write_toml(path: Path, data: dict, comments: list[str] | None = None) -> None:
    lines = _toml_dict_to_lines(data)
    if comments:
        header = [f"# {line}" for line in comments]
        lines = header + [""] + lines
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _load_run_wdm_nli_simulation(nli_script_path: Path):
    module_name = "gnlse_examples_nli_runtime"
    module_dir = str(nli_script_path.parent)
    if module_dir not in sys.path:
        sys.path.insert(0, module_dir)
    spec = importlib.util.spec_from_file_location(module_name, nli_script_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Unable to import module from {nli_script_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    run_fn = getattr(module, "run_wdm_nli_simulation", None)
    if run_fn is None:
        raise AttributeError(f"run_wdm_nli_simulation not found in {nli_script_path}")
    return run_fn


def _safe_loss_db_per_m(system: System, channel_idx: int) -> float:
    freqs = system.wdm.frequency_grid()
    center_freq = float(freqs[channel_idx])
    center_wl = c0 / center_freq
    loss_profile = getattr(system.fiber, "loss_profile", None)
    if callable(loss_profile):
        loss = np.asarray(loss_profile(np.array([center_wl], dtype=float)), dtype=float).reshape(-1)
        if loss.size:
            return float(loss[0])
    losses = getattr(system.fiber, "losses", None)
    if losses is not None:
        vals = np.asarray(losses, dtype=float).reshape(-1)
        if vals.size:
            return float(vals[-1])
    return 0.0


def _safe_beta2_ps2_per_m(system: System, channel_idx: int) -> float:
    freqs = system.wdm.frequency_grid()
    try:
        _, beta2_grid = system.beta_grids(freqs)
        beta2_val = float(np.asarray(beta2_grid, dtype=float)[0, channel_idx])
    except Exception:
        beta2_val = float(getattr(system.fiber, "beta2", 0.0) or 0.0)
    return beta2_val * 1e24


def _compute_min_samples_per_symbol_for_nyquist(
    *,
    symbol_rate_gbd: float,
    channel_spacing_thz: float,
    n_channels: int,
    pulse_shape: str,
    rrc_rolloff: float,
) -> int:
    symbol_rate_thz = float(symbol_rate_gbd) * 1e-3
    if symbol_rate_thz <= 0.0:
        raise ValueError("symbol_rate_gbd must be positive")
    max_offset_thz = channel_spacing_thz * (n_channels - 1) / 2.0
    if pulse_shape == "rrc":
        effective_bw_factor = 1.0 + float(rrc_rolloff)
    else:
        effective_bw_factor = 1.0

    rhs = (2.0 * max_offset_thz / symbol_rate_thz) + effective_bw_factor
    sps = int(np.ceil(rhs))
    return max(sps, 2)


def _build_ssfm_runtime_config(
    *,
    template_cfg: dict,
    system: System,
    baud_rate_hz: float,
    launch_channel_w: float,
    channel_idx: int,
    out_dir: Path,
    baud_tag: str,
) -> dict:
    cfg = copy.deepcopy(template_cfg)

    mod = cfg.setdefault("modulation", {})
    pulse_shape = str(mod.get("pulse_shape", "nyquist_rect"))
    rrc_rolloff = float(mod.get("rrc_rolloff", 0.0))
    mod["symbol_rate_gbd"] = float(baud_rate_hz * 1e-9)

    wdm = cfg.setdefault("wdm", {})
    wdm["n_channels"] = 5
    spacing = float(system.channel_spacing) if system.channel_spacing is not None else float(np.mean(np.diff(system.wdm.frequency_grid())))
    wdm["channel_spacing_thz"] = float(spacing * 1e-12)
    wdm["power_per_channel_w"] = float(launch_channel_w)

    mod["samples_per_symbol"] = _compute_min_samples_per_symbol_for_nyquist(
        symbol_rate_gbd=float(mod["symbol_rate_gbd"]),
        channel_spacing_thz=float(wdm["channel_spacing_thz"]),
        n_channels=int(wdm["n_channels"]),
        pulse_shape=pulse_shape,
        rrc_rolloff=rrc_rolloff,
    )

    freqs = system.wdm.frequency_grid()
    center_freq = float(freqs[channel_idx])
    fiber = cfg.setdefault("fiber", {})
    fiber["wavelength_nm"] = float((c0 / center_freq) * 1e9)
    fiber["fiber_length_m"] = float(system.fiber_length)
    fiber["nonlinearity"] = float(getattr(system.fiber, "gamma", 1.3e-3))
    fiber["loss_db_per_m"] = 0.0
    fiber["betas"] = [float(_safe_beta2_ps2_per_m(system, channel_idx))]

    output = cfg.setdefault("output", {})
    output["save_dir"] = str(out_dir / "ssfm")
    output["save_name"] = f"ssfm_constellation_{baud_tag}.png"
    output["show_plot"] = False

    cache = cfg.setdefault("cache", {})
    cache.setdefault("mode", "recompute")

    return cfg


def _extract_ssfm_center_nli_w(payload: dict) -> float | None:
    try:
        value = payload["power_report"]["center_channel"]["nli_power_avg_w"]
        if value is None:
            return None
        out = float(value)
        if not np.isfinite(out):
            return None
        return out
    except Exception:
        return None


def _prepare_ssfm_runtime(out_dir: Path) -> dict | None:
    nli_script_path = Path(
        str(Path.home() / "sw" / "gnlse-python" / "examples" / "nli" / "nli.py")
    )
    cfg_template_path = Path(
        str(Path.home() / "sw" / "gnlse-python" / "input" / "wdm_nli_config.toml")
    )
    if not nli_script_path.exists():
        nli_script_path = _DEFAULT_GNLSE_NLI_PY
    if not cfg_template_path.exists():
        cfg_template_path = _DEFAULT_GNLSE_WDM_CONFIG

    if not nli_script_path.exists() or not cfg_template_path.exists():
        lg.warning(
            "SSFM disabled: missing gnlse resources. script={}, template={}",
            nli_script_path,
            cfg_template_path,
        )
        return None

    try:
        run_fn = _load_run_wdm_nli_simulation(nli_script_path)
        template_cfg = _toml_load(cfg_template_path)
        if not isinstance(template_cfg, dict):
            raise TypeError("Template TOML root is not a mapping")
    except Exception as exc:
        lg.warning("SSFM disabled: could not initialize gnlse runner ({})", exc)
        return None

    runtime_toml_path = Path(__file__).resolve().parents[1] / "input" / _SSFM_RUNTIME_TOML_NAME
    lg.info(
        "SSFM enabled via gnlse: script={}, template={}, runtime_toml={}",
        nli_script_path,
        cfg_template_path,
        runtime_toml_path,
    )
    return {
        "run_fn": run_fn,
        "template_cfg": template_cfg,
        "runtime_toml_path": runtime_toml_path,
        "out_dir": out_dir,
    }


def _compute_ssfm_center_nli(
    ssfm_ctx: dict,
    *,
    system: System,
    baud_rate_hz: float,
    launch_channel_w: float,
    channel_idx: int,
    baud_tag: str,
) -> float | None:
    runtime_cfg = _build_ssfm_runtime_config(
        template_cfg=ssfm_ctx["template_cfg"],
        system=system,
        baud_rate_hz=baud_rate_hz,
        launch_channel_w=launch_channel_w,
        channel_idx=channel_idx,
        out_dir=ssfm_ctx["out_dir"],
        baud_tag=baud_tag,
    )
    runtime_toml_path = Path(ssfm_ctx["runtime_toml_path"])
    _write_toml(runtime_toml_path, runtime_cfg, comments=_SSFM_TOML_HEADER)
    payload = ssfm_ctx["run_fn"](runtime_toml_path)
    return _extract_ssfm_center_nli_w(payload)

def _parse_float_list(values: str) -> list[float]:
    return [float(x.strip()) for x in values.split(",") if x.strip()]


def _geometric_baud_rates(min_gbaud: float, max_gbaud: float, n_points: int) -> list[float]:
    if min_gbaud <= 0.0 or max_gbaud <= 0.0:
        raise ValueError("Geometric baud-rate bounds must be positive.")
    if max_gbaud < min_gbaud:
        raise ValueError("max_gbaud must be >= min_gbaud.")
    if n_points < 2:
        raise ValueError("n_points must be at least 2.")
    return [float(x) for x in np.geomspace(min_gbaud, max_gbaud, int(n_points))]


def _safe_tag(value: float) -> str:
    text = f"{value:.6e}"
    return text.replace("+", "").replace("-", "m").replace(".", "p")


def _fit_exponent(x_values: np.ndarray, values_w: np.ndarray) -> float:
    mask = np.isfinite(x_values) & np.isfinite(values_w) & (x_values > 0.0) & (values_w > 0.0)
    if int(np.count_nonzero(mask)) < 2:
        return float("nan")
    coeffs = np.polyfit(np.log(x_values[mask]), np.log(values_w[mask]), 1)
    return float(coeffs[0])


def _disable_dbm_axis_grouping(ax: plt.Axes) -> None:
    formatter = ScalarFormatter(useOffset=False)
    formatter.set_scientific(False)
    ax.yaxis.set_major_formatter(formatter)
    ax.yaxis.offsetText.set_visible(False)


def _set_baud_rate(system: System, baud_rate_hz: float) -> None:
    system.pulse.baud_rate = float(baud_rate_hz)
    system.pulse.T0 = 1.0 / float(baud_rate_hz)
    if system.pulse_config is not None:
        system.pulse_config.baud_rate = float(baud_rate_hz)


def _build_constant_launch_vector(system: System, launch_dbm: float | None) -> np.ndarray:
    if launch_dbm is not None:
        launch_w = float(dBm2watt(launch_dbm))
    else:
        launch_w = float(_resolve_launch_powers(
            system,
            profile_path=None,
            launch_csv_path=None,
            use_profile=False,
        )[0])
    return np.full(system.n_channels, launch_w, dtype=float)


def _scaling_series(
    rows: list[dict],
    plot_pcfm_total_and_sci: bool,
) -> dict[str, np.ndarray]:
    series = {
        "TD 64-QAM": np.array([row["td_channel_w"] for row in rows], dtype=float),
        "TD Gaussian": np.array([row["td_gaussian_channel_w"] for row in rows], dtype=float),
    }
    if plot_pcfm_total_and_sci:
        series["PCFM total"] = np.array([row["pcfm_channel_w"] for row in rows], dtype=float)
        series["PCFM SCI"] = np.array([row["pcfm_sci_channel_w"] for row in rows], dtype=float)
    series["PCFM XCI"] = np.array([row["pcfm_xci_channel_w"] for row in rows], dtype=float)
    series["PCFM XCI asymptotic"] = np.array(
        [row["analytic_limit_channel_w"] for row in rows],
        dtype=float,
    )
    if rows and "pcfm_eq18_xci_channel_w" in rows[0]:
        series["PCFM XCI Eq18"] = np.array([row["pcfm_eq18_xci_channel_w"] for row in rows], dtype=float)
    if any("ssfm_channel_w" in row for row in rows):
        series["SSFM"] = np.array([row.get("ssfm_channel_w", np.nan) for row in rows], dtype=float)
    return series


def _center_channel_analytic_limit(system: System, launch_channel_w: float, channel_idx: int) -> float:
    """First-order flat-profile PCFM-XCI asymptote for the selected CUT."""
    launch = np.full(system.wdm.frequency_grid().size, float(launch_channel_w), dtype=float)
    return pcfm_general(
        system,
        channel_idx=channel_idx,
        launch_powers_w=launch,
        use_beta2_eff=True,
        log_order=1,
    )


def _center_channel_eq18_xci(system: System, launch_channel_w: float, channel_idx: int) -> float:
    launch = np.full(system.wdm.frequency_grid().size, float(launch_channel_w), dtype=float)
    return pcfm_general(
        system,
        channel_idx=channel_idx,
        launch_powers_w=launch,
        use_beta2_eff=True,
        xci_model="eq18",
    )


def _save_figure(fig: plt.Figure, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(out_path, dpi=260)
    lg.success("Plot saved: {}", out_path.resolve())


def _plot_scaling(
    rows: list[dict],
    out_path: Path,
    base_system: System,
    channel_idx: int,
    band_label: str,
    channel_freq_thz: float,
    launch_powers_w: np.ndarray,
    plot_pcfm_total_and_sci: bool,
) -> None:
    baud_gbaud = np.array([row["baud_rate_gbaud"] for row in rows], dtype=float)
    series = _scaling_series(rows, plot_pcfm_total_and_sci)
    fig, ax = plt.subplots(figsize=scale_figsize_to_ieee_column(5.2, 3.4))
    colors = plt.rcParams.get("axes.prop_cycle", None)
    palette = colors.by_key().get("color", []) if colors is not None else []
    for idx, (label, values) in enumerate(series.items()):
        color = palette[idx % len(palette)] if palette else None
        ax.plot(
            baud_gbaud,
            watt2dBm(np.maximum(np.asarray(values, dtype=float), 1e-18)),
            marker="o",
            markersize=3,
            markerfacecolor="none",
            markeredgewidth=0.9,
            linewidth=1.0,
            color=color,
            label=f"{label} (p={_fit_exponent(baud_gbaud * 1e9, values):.3f})",
        )
    # plot also the scaling function for reference: linear relation in baud rate, normalized to the first point of PCFM XCI
    ref_baud = baud_gbaud[0] * 1e9
    ref_value = series["PCFM XCI"][0] if series["PCFM XCI"].size else 1.0
    scaling_baud = np.array([ref_baud, baud_gbaud[-1] * 1e9], dtype=float)
    scaling_values = ref_value * (scaling_baud / ref_baud)**(-1.0)  # inverse linear scaling as a reference
    ax.plot(
        scaling_baud / 1e9,
        watt2dBm(np.maximum(np.asarray(scaling_values, dtype=float), 1e-18)),
        linestyle="--",
        color="gray",
        label="linear scaling reference",
    )

    ax.set_xscale("log")
    ax.set_xlabel("Baud rate [GBaud]")
    ax.set_ylabel("Center-channel NLI power [dBm]")
    _disable_dbm_axis_grouping(ax)
    ax.set_title(
        _format_scaling_plot_title(
            base_system,
            sweep_axis="baud",
            channel_idx=channel_idx,
            band_label=band_label,
            launch_powers_w=launch_powers_w,
            channel_freq_thz=channel_freq_thz,
        )
    )
    ax.grid(True, which="both", alpha=0.25)
    ax.legend(fontsize=7)
    _save_figure(fig, out_path)
    plt.close(fig)


def _plot_normalized_scaling(
    rows: list[dict],
    out_path: Path,
    base_system: System,
    channel_idx: int,
    band_label: str,
    channel_freq_thz: float,
    launch_powers_w: np.ndarray,
    plot_pcfm_total_and_sci: bool,
) -> None:
    baud_gbaud = np.array([row["baud_rate_gbaud"] for row in rows], dtype=float)
    series = _scaling_series(rows, plot_pcfm_total_and_sci)
    fig, ax = plt.subplots(figsize=scale_figsize_to_ieee_column(5.2, 3.4))
    colors = plt.rcParams.get("axes.prop_cycle", None)
    palette = colors.by_key().get("color", []) if colors is not None else []
    for idx, (label, values) in enumerate(series.items()):
        color = palette[idx % len(palette)] if palette else None
        ref = float(values[0]) if values.size else 1.0
        normalized = values / ref if ref > 0.0 else values
        ax.plot(
            baud_gbaud,
            normalized,
            marker="o",
            markersize=3,
            markerfacecolor="none",
            markeredgewidth=0.9,
            linewidth=1.0,
            color=color,
            label=label,
        )
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Baud rate [GBaud]")
    ax.set_ylabel("Normalized center-channel NLI power")
    ax.set_title(
        _format_scaling_plot_title(
            base_system,
            sweep_axis="baud",
            channel_idx=channel_idx,
            band_label=band_label,
            launch_powers_w=launch_powers_w,
            channel_freq_thz=channel_freq_thz,
        )
    )
    ax.grid(True, which="both", alpha=0.25)
    ax.legend(fontsize=7)
    _save_figure(fig, out_path)
    plt.close(fig)


def run_baud_sweep(
    cfg_path: Path,
    baud_rates_gbaud: list[float],
    out_dir: Path,
    launch_dbm: float | None,
    pcfm_numeric_xci: bool | None,
    pcfm_eq18_xci: bool | None,
    recompute_td: bool | None,
    recompute_pcfm: bool | None,
    exclude_self_channel: bool | None = None,
    run_ssfm_when_standalone: bool = False,
) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    rows: list[dict] = []

    base_system = System.from_toml(cfg_path)
    runtime_cfg = _load_pcfm_runtime_config(base_system)
    run_flags = _resolve_scaling_run_flags(
        base_system,
        pcfm_numeric_xci=pcfm_numeric_xci,
        pcfm_eq18_xci=pcfm_eq18_xci,
        recompute_td=recompute_td,
        recompute_pcfm=recompute_pcfm,
        exclude_self_channel=exclude_self_channel,
    )
    pcfm_numeric_xci = run_flags["pcfm_numeric_xci"]
    pcfm_eq18_xci = run_flags["pcfm_eq18_xci"]
    recompute_td = run_flags["recompute_td"]
    recompute_pcfm = run_flags["recompute_pcfm"]
    exclude_self_channel = run_flags["exclude_self_channel"]
    plot_pcfm_total_and_sci = bool(runtime_cfg["plot_pcfm_total_and_sci"])
    center_idx, band_label = _select_scaling_channel(base_system)
    freqs = base_system.wdm.frequency_grid()
    channel_freq_thz = float(freqs[center_idx] * 1e-12)
    if launch_dbm is not None:
        title_launch_vec = np.full(base_system.n_channels, float(dBm2watt(launch_dbm)), dtype=float)
    else:
        title_launch_vec = _build_constant_launch_vector(base_system, None)
    lg.info(
        "Selected center channel idx={} in band={} at {:.6f} THz.".format(
            center_idx, band_label, channel_freq_thz
        )
    )

    ssfm_ctx = _prepare_ssfm_runtime(out_dir) if run_ssfm_when_standalone else None

    for baud_gbaud in baud_rates_gbaud:
        system = System.from_toml(cfg_path)
        baud_hz = float(baud_gbaud) * 1e9
        _set_baud_rate(system, baud_hz)
        launch_vec = _build_constant_launch_vector(system, launch_dbm)

        baud_tag = f"R{_safe_tag(baud_gbaud)}GBd"
        profile_path = out_dir / f"flat_profile_{baud_tag}.npy"
        _write_flat_profile(profile_path, system, launch_powers_w=launch_vec)
        profile_power_tag = _power_profile_hash(system, profile_path)
        cache_tag = f"{baud_tag}_prof{profile_power_tag}"
        output_over_launch_signal_power_ratio = _output_over_launch_signal_power_ratio(
            system=system,
            profile_path=profile_path,
            launch_powers_w=launch_vec,
        )

        ccfs = collision_coeffs_system_uwb(
            system,
            ipulse=1,
            recompute=recompute_td,
            profile_path=profile_path,
        )
        td_tag = f"{cache_tag}_{'xci' if exclude_self_channel else 'all'}"
        td_cache = _nlin_cache_path(
            profile_path=profile_path,
            use_kappa=True,
            use_x_mode=True,
            extra_tag=td_tag,
        )
        nlin_td = total_nlin_uwb(
            system,
            ccfs,
            use_kappa=True,
            use_x_mode=True,
            launch_powers_w=launch_vec,
            exclude_self_channel=exclude_self_channel,
            cache_path=td_cache,
            recompute=recompute_td,
        )
        td_vec = _launch_referenced_nlin_to_output_power(
            nlin_td,
            output_over_launch_signal_power_ratio,
        )

        const_pref, sum_a, sum_b = _td_modulation_components(
            system,
            ccfs,
            launch_vec,
            use_kappa=True,
            use_x_mode=True,
            exclude_self_channel=exclude_self_channel,
        )
        td_gaussian_vec = _launch_referenced_nlin_to_output_power(
            np.asarray(
                const_pref * (gaussian_mu0() * sum_a + sum_b),
                dtype=float,
            ),
            output_over_launch_signal_power_ratio,
        )

        pcfm_cfg = PcfmConfig(
            degree=9,
            include_mci=False,
            use_numeric_sci=True,
            use_numeric_xci=bool(pcfm_numeric_xci),
        )
        pcfm_path = out_dir / f"pcfm_{cache_tag}.npy"
        pcfm_total, pcfm_sci, pcfm_xci = _load_or_compute_pcfm_I(
            system=system,
            profile_path=profile_path,
            launch_powers_w=launch_vec,
            output_path=pcfm_path,
            cfg=pcfm_cfg,
            recompute=recompute_pcfm,
            return_components=True,
        )
        pcfm_total = _launch_referenced_nlin_to_output_power(
            pcfm_total,
            output_over_launch_signal_power_ratio,
        )
        pcfm_sci = _launch_referenced_nlin_to_output_power(
            pcfm_sci,
            output_over_launch_signal_power_ratio,
        )
        pcfm_xci = _launch_referenced_nlin_to_output_power(
            pcfm_xci,
            output_over_launch_signal_power_ratio,
        )

        row = {
            "baud_rate_gbaud": float(baud_gbaud),
            "channel_idx": int(center_idx),
            "band_label": band_label,
            "channel_freq_thz": channel_freq_thz,
            "launch_channel_w": float(launch_vec[center_idx]),
            "td_channel_w": float(td_vec[center_idx]),
            "td_gaussian_channel_w": float(td_gaussian_vec[center_idx]),
            "pcfm_channel_w": float(pcfm_total[center_idx]),
            "pcfm_sci_channel_w": float(pcfm_sci[center_idx]),
            "pcfm_xci_channel_w": float(pcfm_xci[center_idx]),
            "analytic_limit_channel_w": _center_channel_analytic_limit(
                system, float(launch_vec[center_idx]), center_idx
            ) * float(output_over_launch_signal_power_ratio[center_idx]),
        }
        if ssfm_ctx is not None:
            try:
                ssfm_val = _compute_ssfm_center_nli(
                    ssfm_ctx,
                    system=system,
                    baud_rate_hz=baud_hz,
                    launch_channel_w=float(launch_vec[center_idx]),
                    channel_idx=center_idx,
                    baud_tag=baud_tag,
                )
                if ssfm_val is not None:
                    row["ssfm_channel_w"] = float(ssfm_val)
                else:
                    lg.warning("SSFM returned no finite center-channel NLI for {}", baud_tag)
            except Exception as exc:
                lg.warning("SSFM run failed for {}: {}", baud_tag, exc)
        if pcfm_eq18_xci:
            row["pcfm_eq18_xci_channel_w"] = _center_channel_eq18_xci(
                system, float(launch_vec[center_idx]), center_idx
            ) * float(output_over_launch_signal_power_ratio[center_idx])
        rows.append(row)
        msg = (
            "R={:.1f} GBd -> TD={:.3e} W, TD(Gauss)={:.3e} W, PCFM={:.3e} W, "
            "PCFM_SCI={:.3e} W, PCFM_XCI={:.3e} W, Analytic={:.3e} W"
        ).format(
            row["baud_rate_gbaud"],
            row["td_channel_w"],
            row["td_gaussian_channel_w"],
            row["pcfm_channel_w"],
            row["pcfm_sci_channel_w"],
            row["pcfm_xci_channel_w"],
            row["analytic_limit_channel_w"],
        )
        if pcfm_eq18_xci:
            msg += ", PCFM_XCI_Eq18={:.3e} W".format(row["pcfm_eq18_xci_channel_w"])
        if "ssfm_channel_w" in row:
            msg += ", SSFM={:.3e} W".format(row["ssfm_channel_w"])
        lg.info(msg)


    rows.sort(key=lambda item: item["baud_rate_gbaud"])
    baud_rates_hz = np.array([row["baud_rate_gbaud"] * 1e9 for row in rows], dtype=float)
    for key in (
        "td_channel_w",
        "td_gaussian_channel_w",
        "pcfm_channel_w",
        "pcfm_sci_channel_w",
        "pcfm_xci_channel_w",
        "analytic_limit_channel_w",
    ):
        exponent = _fit_exponent(baud_rates_hz, np.array([row[key] for row in rows], dtype=float))
        for row in rows:
            row[f"{key}_scaling_exp"] = exponent
    if any("ssfm_channel_w" in row for row in rows):
        exponent = _fit_exponent(baud_rates_hz, np.array([row.get("ssfm_channel_w", np.nan) for row in rows], dtype=float))
        for row in rows:
            if "ssfm_channel_w" in row:
                row["ssfm_channel_w_scaling_exp"] = exponent
    if pcfm_eq18_xci:
        exponent = _fit_exponent(baud_rates_hz, np.array([row["pcfm_eq18_xci_channel_w"] for row in rows], dtype=float))
        for row in rows:
            row["pcfm_eq18_xci_channel_w_scaling_exp"] = exponent

    csv_path = out_dir / "center_channel_baud_scaling.csv"
    header = [
        "baud_rate_gbaud",
        "channel_idx",
        "band_label",
        "channel_freq_thz",
        "launch_channel_w",
        "td_channel_w",
        "td_gaussian_channel_w",
        "pcfm_channel_w",
        "pcfm_sci_channel_w",
        "pcfm_xci_channel_w",
        "analytic_limit_channel_w",
        "td_channel_w_scaling_exp",
        "td_gaussian_channel_w_scaling_exp",
        "pcfm_channel_w_scaling_exp",
        "pcfm_sci_channel_w_scaling_exp",
        "pcfm_xci_channel_w_scaling_exp",
        "analytic_limit_channel_w_scaling_exp",
    ]
    if any("ssfm_channel_w" in row for row in rows):
        header.extend([
            "ssfm_channel_w",
            "ssfm_channel_w_scaling_exp",
        ])
    if pcfm_eq18_xci:
        header.extend([
            "pcfm_eq18_xci_channel_w",
            "pcfm_eq18_xci_channel_w_scaling_exp",
        ])
    data = np.column_stack([[row.get(name, np.nan) for row in rows] for name in header])
    np.savetxt(csv_path, data, delimiter=",", header=",".join(header), comments="", fmt="%s")

    plot_path = Path("media") / "PCFM" / "center_channel_baud_scaling.pdf"
    _plot_scaling(
        rows,
        plot_path,
        base_system,
        center_idx,
        band_label,
        channel_freq_thz,
        title_launch_vec,
        plot_pcfm_total_and_sci=plot_pcfm_total_and_sci,
    )

    summary_lines = [
        f"Center channel idx={center_idx}, band={band_label}, freq={channel_freq_thz:.6f} THz",
        f"TD mode: {'exclude self-channel (nuB==nuA)' if exclude_self_channel else 'include all channels'}",
        f"TD 64-QAM exponent: {_fit_exponent(baud_rates_hz, np.array([row['td_channel_w'] for row in rows], dtype=float)):.6f}",
        f"TD Gaussian exponent: {_fit_exponent(baud_rates_hz, np.array([row['td_gaussian_channel_w'] for row in rows], dtype=float)):.6f}",
        f"PCFM total exponent: {_fit_exponent(baud_rates_hz, np.array([row['pcfm_channel_w'] for row in rows], dtype=float)):.6f}",
        f"PCFM SCI exponent: {_fit_exponent(baud_rates_hz, np.array([row['pcfm_sci_channel_w'] for row in rows], dtype=float)):.6f}",
        f"PCFM XCI exponent: {_fit_exponent(baud_rates_hz, np.array([row['pcfm_xci_channel_w'] for row in rows], dtype=float)):.6f}",
        f"Analytic limit exponent: {_fit_exponent(baud_rates_hz, np.array([row['analytic_limit_channel_w'] for row in rows], dtype=float)):.6f}",
    ]
    if any("ssfm_channel_w" in row for row in rows):
        summary_lines.append(
            f"SSFM exponent: {_fit_exponent(baud_rates_hz, np.array([row.get('ssfm_channel_w', np.nan) for row in rows], dtype=float)):.6f}"
        )
    if pcfm_eq18_xci:
        summary_lines.append(
            f"PCFM XCI Eq18 exponent: {_fit_exponent(baud_rates_hz, np.array([row['pcfm_eq18_xci_channel_w'] for row in rows], dtype=float)):.6f}"
        )
    summary_path = out_dir / "center_channel_baud_scaling_summary.txt"
    summary_path.write_text("\n".join(summary_lines) + "\n")
    return csv_path, summary_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Sweep baud rate and inspect center-channel TD/PCFM scaling."
    )
    parser.add_argument(
        "--config",
        type=str,
        default="input/pcfm_struct.toml",
        help="Path to system TOML.",
    )
    parser.add_argument(
        "--baud-rates-gbaud",
        type=str,
        default=None,
        help=(
            "Optional comma-separated baud rates in GBaud. "
            "If omitted, uses geometric spacing from --baud-min-gbaud to --baud-max-gbaud."
        ),
    )
    parser.add_argument(
        "--baud-min-gbaud",
        type=float,
        default=10.0,
        help="Minimum baud rate in GBaud for geometric sweep.",
    )
    parser.add_argument(
        "--baud-max-gbaud",
        type=float,
        default=100.0,
        help="Maximum baud rate in GBaud for geometric sweep.",
    )
    parser.add_argument(
        "--baud-npoints",
        type=int,
        default=5,
        help="Number of points for geometric baud-rate sweep.",
    )
    parser.add_argument(
        "--launch-dbm",
        type=float,
        default=None,
        help="Optional uniform launch power override in dBm.",
    )
    parser.add_argument(
        "--pcfm-numeric-xci",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Override [pcfm.run].pcfm_numeric_xci.",
    )
    parser.add_argument(
        "--recompute-td",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Override [pcfm.run].td_mode.",
    )
    parser.add_argument(
        "--recompute-pcfm",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Override [pcfm.run].pcfm_mode.",
    )
    parser.add_argument(
        "--exclude-self-channel",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Override [pcfm.run].td_exclude_self_channel.",
    )
    parser.add_argument(
        "--out-dir",
        type=str,
        default="results/debug/pcfm_baud_scaling",
        help="Output directory for generated profiles, caches, and reports.",
    )
    args = parser.parse_args()

    if args.baud_rates_gbaud is not None:
        baud_rates_gbaud = _parse_float_list(args.baud_rates_gbaud)
    else:
        baud_rates_gbaud = _geometric_baud_rates(
            min_gbaud=float(args.baud_min_gbaud),
            max_gbaud=float(args.baud_max_gbaud),
            n_points=int(args.baud_npoints),
        )
    lg.info("Baud sweep [GBaud]: {}", ", ".join(f"{x:.6g}" for x in baud_rates_gbaud))

    csv_path, summary_path = run_baud_sweep(
        cfg_path=Path(args.config),
        baud_rates_gbaud=baud_rates_gbaud,
        out_dir=Path(args.out_dir),
        launch_dbm=args.launch_dbm,
        pcfm_numeric_xci=args.pcfm_numeric_xci,
        pcfm_eq18_xci=None,
        recompute_td=args.recompute_td,
        recompute_pcfm=args.recompute_pcfm,
        exclude_self_channel=args.exclude_self_channel,
        run_ssfm_when_standalone=True,
    )
    lg.success(f"Saved scaling CSV to {csv_path}")
    lg.success(f"Saved scaling summary to {summary_path}")


if __name__ == "__main__":
    main()
